# Netlify settings
[build]
    command = "cd docs/ && bundle plugin install bundler-override && bundle install && jekyll build"
    publish = "docs/_site/"
    environment = { RUBY_VERSION = "3.1.6" }
