apiVersion: v1
kind: Pod
metadata:
  name: setpgrp
  namespace: default
spec:
  containers:
  - name: setpgrp
    image: python:alpine
    command:
    - "/bin/sh"
    - "-c"
    - |
      python -c "
      import os
      os.setpgrp()"
    securityContext:
      privileged: false
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - all
  restartPolicy: Never
