apiVersion: v1
entries:
  node-feature-discovery:
  - apiVersion: v2
    appVersion: v0.9.0
    created: "2021-08-19T19:00:22.213200927Z"
    description: 'Detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels. '
    digest: 550d323bdac39f76537297df33bdfb32d4a81a0cf633e12c57cbec69e2ea24a7
    home: https://github.com/kubernetes-sigs/node-feature-discovery
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/kubernetes-sigs/node-feature-discovery
    type: application
    urls:
    - https://github.com/marquiz/node-feature-discovery/releases/download/v0.9.0/node-feature-discovery-chart-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: v0.8.0
    created: "2021-03-31T08:33:46.678803494Z"
    description: 'Detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels. '
    digest: fabd2b996e450b9caa3412961107dffd3373ec510f0b03cf0c609bbc4d90ccdc
    home: https://github.com/kubernetes-sigs/node-feature-discovery
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/kubernetes-sigs/node-feature-discovery
    type: application
    urls:
    - https://github.com/marquiz/node-feature-discovery/releases/download/v0.1.2/node-feature-discovery-chart-0.8.0+1.tgz
    version: 0.8.0+1
  - apiVersion: v2
    appVersion: v0.7.0
    created: "2021-03-17T09:05:24.437948268Z"
    description: 'Detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels. '
    digest: 7f992e3b7891c049360a571a03d4b01a7d3a35930e5d361745e798fc371c9e49
    home: https://github.com/kubernetes-sigs/node-feature-discovery
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/kubernetes-sigs/node-feature-discovery
    type: application
    urls:
    - https://github.com/marquiz/node-feature-discovery/releases/download/v0.4.0/node-feature-discovery-chart-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: master
    created: "2021-02-26T15:17:09.070635803Z"
    description: 'Detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels. '
    digest: 34f79125c6f3b774b8b9fa5eab5e589bed967e6e8e07e47cff255934e0902df3
    home: https://github.com/kubernetes-sigs/node-feature-discovery
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/kubernetes-sigs/node-feature-discovery
    type: application
    urls:
    - https://github.com/marquiz/node-feature-discovery/releases/download/v0.4.0/node-feature-discovery-chart-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: master
    created: "2021-02-26T15:17:08.769240865Z"
    description: 'Detects hardware features available on each node in a Kubernetes cluster, and advertises those features using node labels. '
    digest: 6a1c49b3336e8b75636727621f6444591e96ca730de0da02eb2c9ee008d4fc17
    home: https://github.com/kubernetes-sigs/node-feature-discovery
    keywords:
    - feature-discovery
    - feature-detection
    - node-labels
    name: node-feature-discovery
    sources:
    - https://github.com/kubernetes-sigs/node-feature-discovery
    type: application
    urls:
    - https://github.com/marquiz/node-feature-discovery/releases/download/v0.3.0/node-feature-discovery-chart-0.3.0.tgz
    version: 0.3.0
generated: "2021-08-19T19:00:22.21217592Z"
