apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

resources:
- master-serviceaccount.yaml
- master-clusterrole.yaml
- master-clusterrolebinding.yaml
- master-service.yaml
- master-deployment.yaml
- worker-daemonset.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - nfd-worker.conf=nfd-worker.conf.example
  name: nfd-worker-conf

patches:
- path: patches/env.yaml
  target:
    labelSelector: app=nfd
    name: nfd.*
- path: patches/securitycontext.yaml
  target:
    labelSelector: app=nfd
    name: nfd.*
- path: patches/master-affinity.yaml
  target:
    labelSelector: app=nfd
    name: nfd-master
- path: patches/worker-mounts.yaml
  target:
    labelSelector: app=nfd
    name: nfd-worker
