apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

resources:
- master-serviceaccount.yaml
- master-clusterrole.yaml
- master-clusterrolebinding.yaml
- master-service.yaml
- master-deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - nfd-worker.conf=nfd-worker.conf.example
  name: nfd-worker-conf
